version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=t_database
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "./manage.py migrate &&
               ./manage.py loaddata fixtures/all.json &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
